### ISSUE TITLE
Required abort() in idle state in order to start a scan.

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/Bug-Reports#116] opened 2016-06-06 15:35 UTC
Killed a scan moving energy.  THis is a know problem.  Recovered prompt and pgm_en position in bluesky and could control the mono.

Tried to start a time scan and required an abort() (as expected).  But Bluesky already believed it was in an idle state.

``````
In [67]: mov(pgm_en,932.575-1.4)

   pgm_en             

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/epics/ca.py:1245: UserWarning: ca.get('XF:23ID1-OP{Mono-Ax:GrtP}Mtr.TDIR') timed out after 1.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/epics/ca.py:1245: UserWarning: ca.get('XF:23ID1-OP{Mono-Ax:GrtP}Mtr.HLS') timed out after 1.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/epics/ca.py:1483: UserWarning: ca.get_timevars('XF:23ID1-OP{Mono}Enrgy-SP') timed out after 5.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
    928.759732        

    928.759732        vs/collection/lib/python3.4/site-packages/epics/ca.py:1245: UserWarning: ca.get('XF:23ID1-OP{Mono-Ax:MirP}Mtr.TDIR') timed out after 1.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
    927.979957        vs/collection/lib/python3.4/site-packages/epics/ca.py:1245: UserWarning: ca.get('XF:23ID1-OP{Mono-Ax:MirP}Mtr.HLS') timed out after 1.00 seconds.
  warnings.warn(msg % (name(chid), timeout))

In [68]: mov(pgm_en,932.575-1.4)

   pgm_en             

    931.223248        


In [69]:  RE(ct(num=1800,delay=2))
---------------------------------------------------------------------------
FailedStatus                              Traceback (most recent call last)
<ipython-input-69-5a4cc0867ee5> in <module>()
----> 1 RE(ct(num=1800,delay=2))

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/run_engine.py in __call__(self, plan, subs, raise_if_interrupted, **metadata_kw)
    576                 exc = self._task.exception()
    577                 if exc is not None:
--> 578                     raise exc
    579             if raise_if_interrupted and self._interrupted:
    580                 raise RunEngineInterrupted("RunEngine was interrupted.")

/home/xf23id1/conda_envs/collection/lib/python3.4/asyncio/tasks.py in _step(***failed resolving arguments***)
    237                 # We use the `send` method directly, because coroutines
    238                 # don't have `__iter__` and `__next__` methods.
--> 239                 result = coro.send(None)
    240             else:
    241                 result = coro.throw(exc)

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/run_engine.py in _run(self)
    855             self.log.error("Run aborted")
    856             self.log.error("%r", err)
--> 857             raise err
    858         finally:
    859             # call stop() on every movable object we ever set()

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/run_engine.py in _run(self)
    800                     yield from asyncio.sleep(0.0001, loop=self.loop)
    801                     if self._exception is not None:
--> 802                         raise self._exception
    803                     # Send last response;
    804                     # get new message but don't process it yet.

FailedStatus: MoveStatus(done=True, pos=pgm_en, elapsed=10.7, success=False, settle_time=0.0)

In [70]: abort()
---------------------------------------------------------------------------
TransitionError                           Traceback (most recent call last)
<ipython-input-70-2fe129fe422b> in <module>()
----> 1 abort()

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/global_state.py in abort()
    156     This function closes over the global RunEngine instance, gs.RE.
    157     """
--> 158     return gs.RE.abort()
    159 
    160 

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/run_engine.py in abort(self, reason)
    740         """
    741         if self.state.is_idle:
--> 742             raise TransitionError("RunEngine is already idle.")
    743         print("Aborting....")
    744         self._interrupted = True

TransitionError: RunEngine is already idle.

In [71]:  RE(ct(num=1800,delay=2))
Transient Scan ID: 64668
Persistent Unique Scan ID: '7dda918e-1a76-4fed-a92b-a8b3cf31bf8b'
+-----------+------------+------------+------------+------------+------------+------------+
|   seq_num |       time |   sclr_ch2 | mono_tempa | mono_tempb |  grt1_temp |  grt2_temp |
+-----------+------------+------------+------------+------------+------------+------------+
|         1 | 11:16:41.7 |       5658 |    302.752 |    302.749 |       33.3 |       28.9 |
|         2 | 11:16:45.1 |       5723 |    302.750 |    302.747 |       33.2 |       28.9 |
|         3 | 11:16:48.5 |       5857 |    302.749 |    302.747 |       33.3 |       28.9 |
|         4 | 11:16:51.8 |       5679 |    302.748 |    302.747 |       33.3 |       28.7 |
|         5 | 11:16:55.3 |       5694 |    302.748 |    302.745 |       33.4 |       28.7 |
|         6 | 11:16:58.8 |       5881 |    302.747 |    302.746 |       33.3 |       28.7 |
|         7 | 11:17:02.2 |       5724 |    302.746 |    302.747 |       33.2 |       28.7 |
|         8 | 11:17:05.6 |       5697 |    302.746 |    302.746 |       33.2 |       28.7 |
|         9 | 11:17:09.0 |       5859 |    302.747 |    302.753 |       33.3 |       28.9 |
|        10 | 11:17:12.3 |       5619 |    302.749 |    302.756 |       33.3 |       28.9 |
|        11 | 11:17:15.8 |       5918 |    302.750 |    302.753 |       33.3 |       28.8 |
|        12 | 11:17:19.1 |       4635 |    302.750 |    302.749 |       33.3 |       28.7 |
|        13 | 11:17:22.5 |         76 |    302.750 |    302.748 |       33.3 |       28.8 |
|        14 | 11:17:25.9 |         76 |    302.751 |    302.753 |       33.0 |       28.8 |
|        15 | 11:17:29.3 |         76 |    302.750 |    302.748 |       33.0 |       28.9 |
|        16 | 11:17:32.6 |         76 |    302.750 |    302.743 |       32.7 |       28.8 |
|        17 | 11:17:36.1 |         76 |    302.750 |    302.743 |       32.5 |       28.7 |
|        18 | 11:17:39.5 |         76 |    302.750 |    302.748 |       32.6 |       28.8 |
|        19 | 11:17:42.9 |         76 |    302.750 |    302.750 |       32.5 |       28.9 |
|        20 | 11:17:46.3 |         76 |    302.751 |    302.750 |       32.4 |       28.7 |
|        21 | 11:17:49.7 |         76 |    302.751 |    302.747 |       32.3 |       28.9 |
|        22 | 11:17:53.1 |         77 |    302.752 |    302.749 |       32.3 |       28.8 |
^CA 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
^C
Your RunEngine is entering a paused state. These are your options for changing
the state of the RunEngine:

resume()  --> will resume the scan
 abort()  --> will kill the scan with an 'aborted' state to indicate
              the scan was interrupted
  stop()  --> will kill the scan with a 'finished' state to indicate
              the scan stopped normally

Pro Tip: Next time, if you want to abort, tap Ctrl+C three times quickly.

Pausing...
Out[71]: ['7dda918e-1a76-4fed-a92b-a8b3cf31bf8b']

In [72]: abort()

`1```
``````

**Comment by stuwilkins** [comment] 2016-06-06 15:46
There is an issue which I should fix with the IOC not setting done when aborting using ^C .. my bad. 

However, it seems that bluesky is not so fault tolerant in this regard.

**Comment by tacaswell** [comment] 2016-06-06 15:50
When the RE exits due to a failed move status it automatically aborts, you do not need to explicitly call `abort` so this is behaving as expected.

The issue is that the `MoveStatus` is still hanging around.  

attn @danielballan did the fix for this not get rolled out or is there still some issues here?

**Comment by danielballan** [comment] 2016-06-06 16:02
@stuwilkins Could you expand on that?

> When the RE exits due to a failed move status it automatically aborts, you do not need to explicitly call abort so this is behaving as expected.

Yes.

> The issue is that the MoveStatus is still hanging around.

What makes you say that? I can't see evidence of that in the Traceback.

> attn @danielballan did the fix for this not get rolled out or is there still some issues here?

Yes. I think you mean [this commit](https://github.com/NSLS-II/bluesky/commit/9f1b997a824cccdd7fafa461c150683dae43d468), which did go in before v0.5.2 was tagged.

**Comment by tacaswell** [comment] 2016-06-24 17:41
This is fixed by https://github.com/NSLS-II/bluesky/pull/497

**Closed as completed by tacaswell** 2016-06-24 17:41 UTC
