### ISSUE TITLE
Conda installation issues

### ISSUE THREAD

**Issue by vivekthampy** [NSLS-II/Bug-Reports#7] opened 2015-05-11 22:02 UTC
Sitting here with @ericdill trying to get the analysis stack set up.  We followed most of the instructions at nsls-ii.github.io --> http://nsls-ii.github.io/install.html

After doing a `conda install csx_analysis` conda is barfing on a glibc error... Here is the output

```
________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => cat .cond
.conda/   .condarc  

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => cat .condarc 
channels:
  - CSX
  - Nikea
  - defaults

create_default_packages:
  - pip

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => conda install csx_analysis
Fetching package metadata: ........
Solving package specifications: .
Package plan for installation in environment /home/vthampy/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda_etc-1                |                0           1 KB
    ncurses-5.9                |                6         774 KB
    csx_configuration-1        |                1           1 KB
    freetype-2.5.2             |                1         2.5 MB
    hdf5-1.8.14                |                0         1.8 MB
    libtiff-4.0.2              |                1         930 KB
    zeromq-4.0.5               |                0         2.6 MB
    fontconfig-2.11.1          |                3         402 KB
    libnetcdf-4.3.2            |                1         881 KB
    cairo-1.12.18              |                3         593 KB
    qt-4.8.6                   |                2        36.4 MB
    certifi-14.05.14           |           py27_1         156 KB
    decorator-3.4.0            |           py27_0           8 KB
    ipython-3.1.0              |           py27_0         3.4 MB
    jsonschema-2.4.0           |           py27_0          51 KB
    lxml-3.4.4                 |           py27_0         2.7 MB
    mistune-0.5.1              |           py27_1         533 KB
    networkx-1.9.1             |           py27_0         934 KB
    numpy-1.9.2                |           py27_0         7.8 MB
    netcdf4-1.1.6              |       np19py27_0         1.2 MB
    openpyxl-2.0.2             |           py27_0         207 KB
    pillow-2.7.0               |           py27_1         771 KB
    ptyprocess-0.4             |           py27_0          19 KB
    pygments-2.0.2             |           py27_0         1.0 MB
    pymongo-2.8                |           py27_0         293 KB
    mongoengine-0.8.7          |           py27_0         253 KB
    pyparsing-2.0.3            |           py27_0          63 KB
    pyzmq-14.6.0               |           py27_0         657 KB
    scipy-0.15.1               |       np19py27_0        37.0 MB
    sip-4.16.5                 |           py27_0         245 KB
    tifffile-0.3.1             |       np19py27_0         112 KB
    xlwt-1.0.0                 |           py27_0         152 KB
    h5py-2.5.0                 |       np19py27_0         2.3 MB
    lmfit-0.8.3                |       np19py27_0         190 KB
    pip-6.1.1                  |           py27_0         1.4 MB
    pyqt-4.11.3                |           py27_1         3.5 MB
    tornado-4.1                |           py27_0         482 KB
    tzlocal-1.1.2              |           py27_0          25 KB
    xraylib-3.1.0.post3        |3_g81f5d6e_np19py27        30.2 MB
    ipython-qtconsole-3.1.0    |           py27_0           4 KB
    matplotlib-1.4.3           |       np19py27_1        44.6 MB
    pandas-0.16.1              |       np19py27_0        10.7 MB
    terminado-0.5              |           py27_0          18 KB
    bubblegum-v0.0.2.post10    |10_g969c7bd_np19py27          55 KB
    channelarchiver-0.0.4.post3|3_g53bf081_np19py27          27 KB
    ipython-notebook-3.1.0     |           py27_1           5 KB
    metadatastore-v0.0.5       |           py27_0          44 KB
    scikit-image-0.11.3        |       np19py27_0        23.8 MB
    vistrails-2.1.4.post1392   |       np19py27_0         5.0 MB
    pims-0.2                   |       np19py27_0          59 KB
    scikit-xray-0.0.3.post117  |117_g5ac2ba4_np19py27         110 KB
    filestore-v0.0.4           |       np19py27_0          34 KB
    dataportal-v0.0.6          |           py27_0          70 KB
    csx_analysis-0.1           |                0          900 B
    ------------------------------------------------------------
                                           Total:       226.9 MB

The following NEW packages will be INSTALLED:

    bubblegum:         v0.0.2.post10-10_g969c7bd_np19py27 
    certifi:           14.05.14-py27_1                    
    channelarchiver:   0.0.4.post3-3_g53bf081_np19py27    
    conda_etc:         1-0                                
    csx_analysis:      0.1-0                              
    csx_configuration: 1-1                                
    dataportal:        v0.0.6-py27_0                      
    decorator:         3.4.0-py27_0                       
    filestore:         v0.0.4-np19py27_0                  
    fontconfig:        2.11.1-3                           
    jsonschema:        2.4.0-py27_0                       
    libnetcdf:         4.3.2-1                            
    lmfit:             0.8.3-np19py27_0                   
    metadatastore:     v0.0.5-py27_0                      
    mistune:           0.5.1-py27_1                       
    mongoengine:       0.8.7-py27_0                       
    ncurses:           5.9-6                              
    netcdf4:           1.1.6-np19py27_0                   
    pillow:            2.7.0-py27_1                       
    pims:              0.2-np19py27_0                     
    ptyprocess:        0.4-py27_0                         
    pymongo:           2.8-py27_0                         
    scikit-xray:       0.0.3.post117-117_g5ac2ba4_np19py27
    terminado:         0.5-py27_0                         
    tifffile:          0.3.1-np19py27_0                   
    tzlocal:           1.1.2-py27_0                       
    vistrails:         2.1.4.post1392-np19py27_0          
    xraylib:           3.1.0.post3-3_g81f5d6e_np19py27    

The following packages will be UPDATED:

    atom:              0.3.7-py27_0      --> 0.3.9-py27_0                       
    cairo:             1.12.18-0         --> 1.12.18-3                          
    curl:              7.30.0-0          --> 7.38.0-0                           
    enaml:             0.9.1-py27_1      --> 0.9.8-py27_0                       
    freetype:          2.4.10-0          --> 2.5.2-1                            
    h5py:              2.3.0-np18py27_0  --> 2.5.0-np19py27_0                   
    hdf5:              1.8.9-1           --> 1.8.14-0                           
    ipython:           2.1.0-py27_2      --> 3.1.0-py27_0                       
    ipython-notebook:  2.1.0-py27_0      --> 3.1.0-py27_1                       
    ipython-qtconsole: 2.1.0-py27_0      --> 3.1.0-py27_0                       
    kiwisolver:        0.1.2-py27_0      --> 0.1.3-py27_0                       
    libtiff:           4.0.2-0           --> 4.0.2-1                            
    lxml:              3.3.5-py27_0      --> 3.4.4-py27_0                       
    matplotlib:        1.4.2-np19py27_0  --> 1.4.3-np19py27_1                   
    networkx:          1.8.1-py27_0      --> 1.9.1-py27_0                       
    numpy:             1.9.1-py27_0      --> 1.9.2-py27_0                       
    openpyxl:          1.8.5-py27_0      --> 2.0.2-py27_0                       
    pandas:            0.14.0-np18py27_0 --> 0.16.1-np19py27_0                  
    pip:               1.5.6-py27_0      --> 6.1.1-py27_0                       
    pygments:          1.6-py27_0        --> 2.0.2-py27_0                       
    pyparsing:         2.0.1-py27_0      --> 2.0.3-py27_0                       
    pyqt:              4.10.4-py27_0     --> 4.11.3-py27_1                      
    python:            2.7.9-2           --> 2.7.9-10                           
    pyzmq:             14.3.0-py27_0     --> 14.6.0-py27_0                      
    qt:                4.8.5-0           --> 4.8.6-2                            
    readline:          6.2-2             --> 6.2-12                             
    scikit-image:      0.10.0-np18py27_0 --> 0.11.3-np19py27_0                  
    scipy:             0.14.0-np18py27_0 --> 0.15.1-np19py27_0                  
    sip:               4.15.5-py27_0     --> 4.16.5-py27_0                      
    tornado:           3.2.1-py27_0      --> 4.1-py27_0                         
    xlwt:              0.7.5-py27_0      --> 1.0.0-py27_0                       
    zeromq:            4.0.4-0           --> 4.0.5-0                            

Proceed ([y]/n)? y   

Fetching packages ...
conda_etc-1-0. 100% |####################################################################################################################| Time: 0:00:00  45.43 kB/s
ncurses-5.9-6. 100% |####################################################################################################################| Time: 0:00:00   8.75 MB/s
csx_configurat 100% |####################################################################################################################| Time: 0:00:00  47.32 kB/s
freetype-2.5.2 100% |####################################################################################################################| Time: 0:00:00  14.36 MB/s
hdf5-1.8.14-0. 100% |####################################################################################################################| Time: 0:00:00  12.72 MB/s
libtiff-4.0.2- 100% |####################################################################################################################| Time: 0:00:00   7.92 MB/s
zeromq-4.0.5-0 100% |####################################################################################################################| Time: 0:00:00   9.57 MB/s
fontconfig-2.1 100% |####################################################################################################################| Time: 0:00:00   3.94 MB/s
libnetcdf-4.3. 100% |####################################################################################################################| Time: 0:00:00  10.50 MB/s
cairo-1.12.18- 100% |####################################################################################################################| Time: 0:00:00   7.94 MB/s
qt-4.8.6-2.tar 100% |####################################################################################################################| Time: 0:00:02  13.41 MB/s
certifi-14.05. 100% |####################################################################################################################| Time: 0:00:00  10.08 MB/s
decorator-3.4. 100% |####################################################################################################################| Time: 0:00:00 350.85 kB/s
ipython-3.1.0- 100% |####################################################################################################################| Time: 0:00:00  15.16 MB/s
jsonschema-2.4 100% |####################################################################################################################| Time: 0:00:00   1.31 MB/s
lxml-3.4.4-py2 100% |####################################################################################################################| Time: 0:00:00  13.35 MB/s
mistune-0.5.1- 100% |####################################################################################################################| Time: 0:00:00   6.33 MB/s
networkx-1.9.1 100% |####################################################################################################################| Time: 0:00:00  10.21 MB/s
numpy-1.9.2-py 100% |####################################################################################################################| Time: 0:00:00  18.73 MB/s
netcdf4-1.1.6- 100% |####################################################################################################################| Time: 0:00:00  11.54 MB/s
openpyxl-2.0.2 100% |####################################################################################################################| Time: 0:00:00   3.24 MB/s
pillow-2.7.0-p 100% |####################################################################################################################| Time: 0:00:00   7.65 MB/s
ptyprocess-0.4 100% |####################################################################################################################| Time: 0:00:00 548.52 kB/s
pygments-2.0.2 100% |####################################################################################################################| Time: 0:00:00   9.61 MB/s
pymongo-2.8-py 100% |####################################################################################################################| Time: 0:00:00   3.78 MB/s
mongoengine-0. 100% |####################################################################################################################| Time: 0:00:00  15.57 MB/s
pyparsing-2.0. 100% |####################################################################################################################| Time: 0:00:00   1.60 MB/s
pyzmq-14.6.0-p 100% |####################################################################################################################| Time: 0:00:00   7.26 MB/s
scipy-0.15.1-n 100% |####################################################################################################################| Time: 0:00:01  19.56 MB/s
sip-4.16.5-py2 100% |####################################################################################################################| Time: 0:00:00   3.58 MB/s
tifffile-0.3.1 100% |####################################################################################################################| Time: 0:00:00   3.39 MB/s
xlwt-1.0.0-py2 100% |####################################################################################################################| Time: 0:00:00   1.87 MB/s
h5py-2.5.0-np1 100% |####################################################################################################################| Time: 0:00:00  10.18 MB/s
lmfit-0.8.3-np 100% |####################################################################################################################| Time: 0:00:00   3.68 MB/s
pip-6.1.1-py27 100% |####################################################################################################################| Time: 0:00:00  11.39 MB/s
pyqt-4.11.3-py 100% |####################################################################################################################| Time: 0:00:00  11.71 MB/s
tornado-4.1-py 100% |####################################################################################################################| Time: 0:00:00   7.60 MB/s
tzlocal-1.1.2- 100% |####################################################################################################################| Time: 0:00:00   2.77 MB/s
xraylib-3.1.0. 100% |####################################################################################################################| Time: 0:00:02  11.70 MB/s
ipython-qtcons 100% |####################################################################################################################| Time: 0:00:00 166.85 kB/s
matplotlib-1.4 100% |####################################################################################################################| Time: 0:00:02  18.07 MB/s
pandas-0.16.1- 100% |####################################################################################################################| Time: 0:00:00  16.72 MB/s
terminado-0.5- 100% |####################################################################################################################| Time: 0:00:00   1.40 MB/s
bubblegum-v0.0 100% |####################################################################################################################| Time: 0:00:00   4.81 MB/s
channelarchive 100% |####################################################################################################################| Time: 0:00:00   1.15 MB/s
ipython-notebo 100% |####################################################################################################################| Time: 0:00:00 163.92 kB/s
metadatastore- 100% |####################################################################################################################| Time: 0:00:00   5.25 MB/s
scikit-image-0 100% |####################################################################################################################| Time: 0:00:01  15.84 MB/s
vistrails-2.1. 100% |####################################################################################################################| Time: 0:00:00  10.50 MB/s
pims-0.2-np19p 100% |####################################################################################################################| Time: 0:00:00   7.01 MB/s
scikit-xray-0. 100% |####################################################################################################################| Time: 0:00:00   1.70 MB/s
filestore-v0.0 100% |####################################################################################################################| Time: 0:00:00   3.75 MB/s
dataportal-v0. 100% |####################################################################################################################| Time: 0:00:00   2.85 MB/s
csx_analysis-0 100% |####################################################################################################################| Time: 0:00:00 143.15 kB/s
Extracting packages ...
[      COMPLETE      ]|#######################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#######################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#######################################################################################################################################| 100%

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => conda update --all
/home/vthampy/anaconda/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/vthampy/anaconda/bin/../lib/libpython2.7.so.1.0)

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => conda installed
/home/vthampy/anaconda/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/vthampy/anaconda/bin/../lib/libpython2.7.so.1.0)

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => conda
/home/vthampy/anaconda/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/vthampy/anaconda/bin/../lib/libpython2.7.so.1.0)

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => conda
/home/vthampy/anaconda/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/vthampy/anaconda/bin/../lib/libpython2.7.so.1.0)

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => source .bas
.bash_aliases         .bash_aliases~        .bash_history         .bash_logout          .bashrc               .bashrc-anaconda.bak  

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => source .bashrc
.bashrc               .bashrc-anaconda.bak  

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => source .bashrcc
-bash: .bashrcc: No such file or directory

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => source ~/.bashrcc
-bash: /home/vthampy/.bashrcc: No such file or directory

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => source ~/.bashrc

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => conda
/home/vthampy/anaconda/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/vthampy/anaconda/bin/../lib/libpython2.7.so.1.0)

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => cond
-bash: cond: command not found

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => CONDA
-bash: CONDA: command not found

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
| => conda
/home/vthampy/anaconda/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/vthampy/anaconda/bin/../lib/libpython2.7.so.1.0)

________________________________________________________________________________
| ~ @ xf23id1-srv1 (vthampy) 
```

**Comment by tacaswell** [comment] 2015-05-12 00:31
I can not reproduce this on srv1 on my account.

It looks like you had multiple versions of anaconda installed and I suspect were getting linking errors due to that.

You also should not install `csx_analysis` (or really _anything_) into the root conda environment.  Some of the configuration requires that the env be activated to set it's self up.

**Comment by danielballan** [comment] 2015-05-12 01:50
Reopening until @vivekthampy reports back with success.

**Comment by ericdill** [comment] 2015-05-12 02:45
@tacaswell was inadvertently correct to close this. We dealt with this by deleting ~/anaconda and reinstalling (miniconda).  

On a side note we HAVE to figure out how to make the extracting step take less time on the controls network.  It is simply embarrassing to have to wait >5 min for `conda create - n analysis csx_analysis`

**Closed as completed by ericdill** 2015-05-12 02:45 UTC

**Comment by danielballan** [comment] 2015-05-12 03:21
To that last point @ericdill, it occurs to me now that a cp or ln command is a decent workaround. (Keep a copy of the environment in some public location.)

**Comment by tacaswell** [comment] 2015-05-12 10:46
Environments are not relocatable, a whole bunch of hard-coded paths are re-written on installation.

**Comment by danielballan** [comment] 2015-05-12 11:23
Right. That was too off-the-cuff of a suggestion. Thanks.
