### ISSUE TITLE
CHX scan does not work

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II/Bug-Reports#74] opened 2016-01-27 20:17 UTC
We tried two way to do scan

1) use a RE(plan)

``` python
In [1]: plan = DeltaScanPlan( [xray_eye1], dcm.b, -0.01,0.01, 10)
In [2]: plan.subs=[ LiveTable( [dcm.b, 'xray_eye1_stats1_total']), LivePlot(x= dcm.b, y='xray_eye1_stats1_total', markersize=10, marker='go' ) ]

In [3]: RE(plan)
```

This is what we got:

```
Scan ID: 1705
Unique ID: 675b4f6b-adfa-472c-a90d-b48ed6864003
+------------+--------------+-----------------------+-----------------------+--------------------------+
|   seq_num  |        time  |  dcm_b_user_readback  |  dcm_b_user_setpoint  |  xray_eye1_stats1_total  |
+------------+--------------+-----------------------+-----------------------+--------------------------+
|         1  |  15:14:08.6  |               -12.72  |               -12.72  |                9.39e+05  |
|         2  |  15:14:10.1  |               -12.71  |               -12.71  |                9.42e+05  |
|         3  |  15:14:11.4  |               -12.71  |               -12.71  |                9.49e+05  |
|         4  |  15:14:12.9  |               -12.71  |               -12.71  |                9.49e+05  |
|         5  |  15:14:14.4  |               -12.71  |               -12.71  |                9.49e+05  |
|         6  |  15:14:15.8  |               -12.70  |               -12.70  |                9.52e+05  |
|         7  |  15:14:17.3  |               -12.70  |               -12.70  |                9.56e+05  |
|         8  |  15:14:18.8  |               -12.70  |               -12.70  |                9.40e+05  |
|         9  |  15:14:20.3  |               -12.70  |               -12.70  |                9.48e+05  |
|        10  |  15:14:21.7  |               -12.70  |               -12.70  |                9.48e+05  |
+------------+--------------+-----------------------+-----------------------+--------------------------+
Run aborted
'token'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-e65fc2a3d422> in <module>()
----> 1 RE(plan)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in __call__(self, plan, subs, **metadata_kw)
    527                 exc = self._task.exception()
    528                 if exc is not None:
--> 529                     raise exc
    530 
    531         return self._run_start_uids

/home/xf11id/conda_envs/collection/lib/python3.5/asyncio/tasks.py in _step(***failed resolving arguments***)
    237                 # We use the `send` method directly, because coroutines
    238                 # don't have `__iter__` and `__next__` methods.
--> 239                 result = coro.send(None)
    240             else:
    241                 result = coro.throw(exc)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _run(self)
    692             logger.error("Run aborted")
    693             logger.error("%s", err)
--> 694             raise err
    695         finally:
    696             self.state = 'idle'

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _run(self)
    665                     logger.debug("Processing message %r", msg)
    666                     self.debug("About to process: {0}, {1}".format(coro, msg))
--> 667                     response = yield from coro(msg)
    668                     self.debug('RE.state: ' + self.state)
    669                     self.debug('msg: {}\n  response: {}'.format(msg, response))

/home/xf11id/conda_envs/collection/lib/python3.5/asyncio/coroutines.py in coro(*args, **kw)
    204         @functools.wraps(func)
    205         def coro(*args, **kw):
--> 206             res = func(*args, **kw)
    207             if isinstance(res, futures.Future) or inspect.isgenerator(res):
    208                 res = yield from res

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _unsubscribe(self, msg)
   1123         _, obj, args, kwargs = msg
   1124         try:
-> 1125             token = kwargs['token']
   1126         except AttributeError:
   1127             token, = args

KeyError: 'token'
```

We also got nothing in the plot. There is some messed up x-axis.

2)  dscan

```
In [4]: dscan(dcm.b,-.01,.01,10,.001)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/ophyd/device.py in __getattr__(self, name)
    545                 # Initial access of signal
--> 546                 cpt = self._sig_attrs[name]
    547                 return cpt.__get__(self, None)

KeyError: '_name'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-4-fce76455f2b8> in <module>()
----> 1 dscan(dcm.b,-.01,.01,10,.001)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/simple_scans.py in __call__(self, motor, start, finish, intervals, time, subs, **kwargs)
    254         original_times = _set_acquire_time(time)
    255         result = super().__call__(motor, start, finish, intervals + 1,
--> 256                                   subs=subs, **kwargs)
    257         _unset_acquire_time(original_times)
    258         return result

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/simple_scans.py in __call__(self, subs, sub_factories, *args, **kwargs)
    141         # Create a sub from each sub_factory.
    142         _update_lists(_subs, _run_factories(sub_factories, self.scan))
--> 143         _update_lists(_subs, _run_factories(self.sub_factories, self.scan))
    144 
    145         # Set up scan attributes.

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/simple_scans.py in _run_factories(factories, scan)
    177     out = {k: list(filterfalse(lambda x: x is None,
    178                                (sf(scan) for sf in v)))
--> 179            for k, v in factories.items()}
    180     gs._SECRET_STASH = out
    181     return out

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/simple_scans.py in <dictcomp>(.0)
    177     out = {k: list(filterfalse(lambda x: x is None,
    178                                (sf(scan) for sf in v)))
--> 179            for k, v in factories.items()}
    180     gs._SECRET_STASH = out
    181     return out

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/simple_scans.py in <genexpr>(.0)
    176     factories = normalize_subs_input(factories)
    177     out = {k: list(filterfalse(lambda x: x is None,
--> 178                                (sf(scan) for sf in v)))
    179            for k, v in factories.items()}
    180     gs._SECRET_STASH = out

/home/xf11id/.ipython/profile_collection/startup/99-bluesky.py in chx_plot_motor(scan)
     15     elif gs.PLOTMODE == 3:
     16         fig = plt.figure()
---> 17     return LivePlot(gs.PLOT_Y, scan.motor._name, fig=fig)
     18 
     19 # this changes the default plotter for *all* classes that

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/ophyd/device.py in __getattr__(self, name)
    547                 return cpt.__get__(self, None)
    548             except KeyError:
--> 549                 raise AttributeError(name)
    550 
    551         attr_names = name.split('.')

AttributeError: _name
```

any idea?

**Comment by danielballan** [comment] 2016-01-27 22:30
Thanks for this good report. The first issue, on scan ID 1705 is now fixed in the master branch of bluesky. I will deploy it first thing tomorrow.

The second issue involves some outdated code in 99-bluesky.py. I can fix that tomorrow as well. If you are curious, the issue is that motors used to have only one field (`_name`) but now it is more complicated: the expose a setpoint, a readback, and potentially more. The LivePlot code in bluesky has become more sophisticated in order to handle that. We'll update the 99-bluesky.py file in your IPython profile as well.

**Comment by yugangzhang** [comment] 2016-01-27 22:38
Thanks! We have to do scan now. Can I 

```
conda update bluesky
```

**Comment by danielballan** [comment] 2016-01-27 22:44
It won't work until Tom re-builds the packages. He is the only one who is allowed to do this. He will do it as soon as he gets home.

Daniel B. Allan
(631) 344-3281
Assistant Computational Scientist
Brookhaven National Lab

**Comment by danielballan** [comment] 2016-01-27 22:46
Actually I found a way around. It may work now if you exit and start IPython again. Use the RE(Plan). dscan will still be broken until tomorrow -- that's a more detailed fix I can't do remotely.

Dan

Daniel B. Allan
(631) 344-3281
Assistant Computational Scientist
Brookhaven National Lab

**Comment by yugangzhang** [comment] 2016-01-27 22:50
I exit ipython and restart it, this is what I got

``` python

In [1]: plan = DeltaScanPlan( [xray_eye1], dcm.b, -0.01,0.01, 10)
In [2]: plan.subs=[ LiveTable( [dcm.b, 'xray_eye1_stats1_total']), LivePlot(x= dcm.b, y='xray_eye1_stats1_total', markersize=10, marker='go' ) ]

In [3]: RE(plan)
Scan ID: 1708
Unique ID: db6e5fe4-76ff-470b-9d04-f345b8c1e991
+------------+--------------+-----------------------+-----------------------+--------------------------+
|   seq_num  |        time  |  dcm_b_user_readback  |  dcm_b_user_setpoint  |  xray_eye1_stats1_total  |
+------------+--------------+-----------------------+-----------------------+--------------------------+
|         1  |  17:48:20.7  |               -12.69  |               -12.69  |                9.48e+05  |
|         2  |  17:48:22.1  |               -12.68  |               -12.68  |                9.46e+05  |
|         3  |  17:48:23.5  |               -12.68  |               -12.68  |                9.55e+05  |
|         4  |  17:48:24.9  |               -12.68  |               -12.68  |                9.52e+05  |
|         5  |  17:48:26.2  |               -12.68  |               -12.68  |                9.48e+05  |
|         6  |  17:48:27.7  |               -12.67  |               -12.67  |                9.45e+05  |
|         7  |  17:48:29.1  |               -12.67  |               -12.67  |                9.42e+05  |
|         8  |  17:48:30.5  |               -12.67  |               -12.67  |                9.45e+05  |
|         9  |  17:48:32.0  |               -12.67  |               -12.67  |                9.49e+05  |
|        10  |  17:48:33.4  |               -12.67  |               -12.67  |                9.49e+05  |
+------------+--------------+-----------------------+-----------------------+--------------------------+
Run aborted
not enough values to unpack (expected 1, got 0)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _unsubscribe(self, msg)
   1124         try:
-> 1125             token = kwargs['token']
   1126         except KeyError:

KeyError: 'token'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-3-e65fc2a3d422> in <module>()
----> 1 RE(plan)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in __call__(self, plan, subs, **metadata_kw)
    527                 exc = self._task.exception()
    528                 if exc is not None:
--> 529                     raise exc
    530 
    531         return self._run_start_uids

/home/xf11id/conda_envs/collection/lib/python3.5/asyncio/tasks.py in _step(***failed resolving arguments***)
    237                 # We use the `send` method directly, because coroutines
    238                 # don't have `__iter__` and `__next__` methods.
--> 239                 result = coro.send(None)
    240             else:
    241                 result = coro.throw(exc)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _run(self)
    692             logger.error("Run aborted")
    693             logger.error("%s", err)
--> 694             raise err
    695         finally:
    696             self.state = 'idle'

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _run(self)
    665                     logger.debug("Processing message %r", msg)
    666                     self.debug("About to process: {0}, {1}".format(coro, msg))
--> 667                     response = yield from coro(msg)
    668                     self.debug('RE.state: ' + self.state)
    669                     self.debug('msg: {}\n  response: {}'.format(msg, response))

/home/xf11id/conda_envs/collection/lib/python3.5/asyncio/coroutines.py in coro(*args, **kw)
    204         @functools.wraps(func)
    205         def coro(*args, **kw):
--> 206             res = func(*args, **kw)
    207             if isinstance(res, futures.Future) or inspect.isgenerator(res):
    208                 res = yield from res

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _unsubscribe(self, msg)
   1125             token = kwargs['token']
   1126         except KeyError:
-> 1127             token, = args
   1128         self.unsubscribe(token)
   1129         self._temp_callback_ids.remove(token)

ValueError: not enough values to unpack (expected 1, got 0)

```

It seems like that the scan works, but the plot doesn't work. I am not sure what x should be in 
`LivePlot(x= dcm.b,`

**Comment by danielballan** [comment] 2016-01-27 22:53
This is my fault. My hard to debug from the train about to go underground. Hold tight. What is the beamline phone #?

Sent from Outlook Mobilehttps://aka.ms/qtex0l

On Wed, Jan 27, 2016 at 2:50 PM -0800, "Yugang Zhang" <notifications@github.com<mailto:notifications@github.com>> wrote:

I exit ipython and restart it, this is what I got

In [1]: plan = DeltaScanPlan( [xray_eye1], dcm.b, -0.01,0.01, 10)
In [2]: plan.subs=[ LiveTable( [dcm.b, 'xray_eye1_stats1_total']), LivePlot(x= dcm.b, y='xray_eye1_stats1_total', markersize=10, marker='go' ) ]

In [3]: RE(plan)
Scan ID: 1708
Unique ID: db6e5fe4-76ff-470b-9d04-f345b8c1e991
+------------+--------------+-----------------------+-----------------------+--------------------------+
|   seq_num  |        time  |  dcm_b_user_readback  |  dcm_b_user_setpoint  |  xray_eye1_stats1_total  |
+------------+--------------+-----------------------+-----------------------+--------------------------+
|         1  |  17:48:20.7  |               -12.69  |               -12.69  |                9.48e+05  |
|         2  |  17:48:22.1  |               -12.68  |               -12.68  |                9.46e+05  |
|         3  |  17:48:23.5  |               -12.68  |               -12.68  |                9.55e+05  |
|         4  |  17:48:24.9  |               -12.68  |               -12.68  |                9.52e+05  |
|         5  |  17:48:26.2  |               -12.68  |               -12.68  |                9.48e+05  |
|         6  |  17:48:27.7  |               -12.67  |               -12.67  |                9.45e+05  |
|         7  |  17:48:29.1  |               -12.67  |               -12.67  |                9.42e+05  |
|         8  |  17:48:30.5  |               -12.67  |               -12.67  |                9.45e+05  |
|         9  |  17:48:32.0  |               -12.67  |               -12.67  |                9.49e+05  |
|        10  |  17:48:33.4  |               -12.67  |               -12.67  |                9.49e+05  |
+------------+--------------+-----------------------+-----------------------+--------------------------+
Run aborted

## not enough values to unpack (expected 1, got 0)

KeyError                                  Traceback (most recent call last)
/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _unsubscribe(self, msg)
   1124         try:
-> 1125             token = kwargs['token']
   1126         except KeyError:

KeyError: 'token'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-3-e65fc2a3d422> in <module>()
----> 1 RE(plan)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in **call**(self, plan, subs, **metadata_kw)
    527                 exc = self._task.exception()
    528                 if exc is not None:
--> 529                     raise exc
    530
    531         return self._run_start_uids

/home/xf11id/conda_envs/collection/lib/python3.5/asyncio/tasks.py in _step(**_failed resolving arguments**_)
    237                 # We use the `send` method directly, because coroutines
    238                 # don't have `__iter__`and`**next**` methods.
--> 239                 result = coro.send(None)
    240             else:
    241                 result = coro.throw(exc)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _run(self)
    692             logger.error("Run aborted")
    693             logger.error("%s", err)
--> 694             raise err
    695         finally:
    696             self.state = 'idle'

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _run(self)
    665                     logger.debug("Processing message %r", msg)
    666                     self.debug("About to process: {0}, {1}".format(coro, msg))
--> 667                     response = yield from coro(msg)
    668                     self.debug('RE.state: ' + self.state)
    669                     self.debug('msg: {}\n  response: {}'.format(msg, response))

/home/xf11id/conda_envs/collection/lib/python3.5/asyncio/coroutines.py in coro(_args, *_kw)
    204         @functools.wraps(func)
    205         def coro(_args, *_kw):
--> 206             res = func(_args, *_kw)
    207             if isinstance(res, futures.Future) or inspect.isgenerator(res):
    208                 res = yield from res

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _unsubscribe(self, msg)
   1125             token = kwargs['token']
   1126         except KeyError:
-> 1127             token, = args
   1128         self.unsubscribe(token)
   1129         self._temp_callback_ids.remove(token)

ValueError: not enough values to unpack (expected 1, got 0)

It seems like that the scan works, but the plot doesn't work. I am not sure what x should be in
LivePlot(x= dcm.b,

**Comment by yugangzhang** [comment] 2016-01-27 23:00
X1411

**Comment by danielballan** [comment] 2016-01-27 23:02
10 minutes. It should be as simple as conda update, but sadly it is not. Soon!

Sent from Outlook Mobilehttps://aka.ms/qtex0l

On Wed, Jan 27, 2016 at 3:00 PM -0800, "Yugang Zhang" <notifications@github.com<mailto:notifications@github.com>> wrote:

X1411

**Comment by tacaswell** [comment] 2016-01-27 23:42
You should be able to update via conda now,

**Comment by yugangzhang** [comment] 2016-01-27 23:49
```
In [20]: RE.ignore_callback_exceptions=False

In [21]: RE(plan)
Scan ID: 1716
Unique ID: cc6e3fc5-77f1-4fc9-ae57-a88ce776d02f
Run aborted
name 'get_session_manager' is not defined
+-----------+--------+-----------------------+-----------------------+--------------------------+
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-21-e65fc2a3d422> in <module>()
----> 1 RE(plan)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in __call__(self, plan, subs, **metadata_kw)
    527                 exc = self._task.exception()
    528                 if exc is not None:
--> 529                     raise exc
    530 
    531         return self._run_start_uids

/home/xf11id/conda_envs/collection/lib/python3.5/asyncio/tasks.py in _step(***failed resolving arguments***)
    237                 # We use the `send` method directly, because coroutines
    238                 # don't have `__iter__` and `__next__` methods.
--> 239                 result = coro.send(None)
    240             else:
    241                 result = coro.throw(exc)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _run(self)
    692             logger.error("Run aborted")
    693             logger.error("%s", err)
--> 694             raise err
    695         finally:
    696             self.state = 'idle'

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _run(self)
    665                     logger.debug("Processing message %r", msg)
    666                     self.debug("About to process: {0}, {1}".format(coro, msg))
--> 667                     response = yield from coro(msg)
    668                     self.debug('RE.state: ' + self.state)
    669                     self.debug('msg: {}\n  response: {}'.format(msg, response))

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _open_run(self, msg)
    804         doc = dict(uid=self._run_start_uid, time=ttime.time(),
    805                    **self._metadata_per_run)
--> 806         yield from self.emit(DocumentNames.start, doc)
    807         self.debug("*** Emitted RunStart:\n%s" % doc)
    808         logger.debug("Starting new run:  %s", self._run_start_uid)

/home/xf11id/conda_envs/collection/lib/python3.5/asyncio/coroutines.py in coro(*args, **kw)
    204         @functools.wraps(func)
    205         def coro(*args, **kw):
--> 206             res = func(*args, **kw)
    207             if isinstance(res, futures.Future) or inspect.isgenerator(res):
    208                 res = yield from res

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in emit(self, name, doc)
   1135         self._lossless_cb_registry.process(name, name.name, doc)
   1136         if name != DocumentNames.event:
-> 1137             self.dispatcher.process(name, doc)
   1138             logger.info("Emitting %s document: %r", name.name, doc)
   1139         else:

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in process(self, name, doc)
   1157 
   1158     def process(self, name, doc):
-> 1159         self.cb_registry.process(name, name.name, doc)
   1160 
   1161     def subscribe(self, name, func):

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/utils.py in process(self, sig, *args, **kwargs)
    149             for cid, func in self.callbacks[sig].items():
    150                 try:
--> 151                     func(*args, **kwargs)
    152                 except ReferenceError:
    153                     self._remove_proxy(func)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/utils.py in __call__(self, *args, **kwargs)
    230             mtd = self.func
    231         # invoke the callable and return the result
--> 232         return mtd(*args, **kwargs)
    233 
    234     def __eq__(self, other):

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/callbacks/core.py in __call__(self, name, doc)
     23     def __call__(self, name, doc):
     24         "Dispatch to methods expecting particular doc types."
---> 25         return getattr(self, name)(doc)
     26 
     27     def event(self, doc):

/home/xf11id/.ipython/profile_collection/startup/99-bluesky.py in start(self, doc)
     87             f.write('#T %s (Seconds)\n' % self.acquisition_time)
     88         # write the motor positions
---> 89         session_manager = get_session_manager()
     90         pos = session_manager.get_positioners()
     91         positions = [str(v.position) for k, v in sorted(pos.items())]

NameError: name 'get_session_manager' is not defined

```

**Comment by yugangzhang** [comment] 2016-01-27 23:55
```
In [4]: RE(plan)Scan ID: 1717
Unique ID: 2b52e9e3-b547-46de-80b8-29c1239a3357
+------------+--------------+-----------------------+-----------------------+--------------------------+
|   seq_num  |        time  |  dcm_b_user_readback  |  dcm_b_user_setpoint  |  xray_eye1_stats1_total  |
+------------+--------------+-----------------------+-----------------------+--------------------------+
Run aborted
Unrecognized marker style go
+------------+--------------+-----------------------+-----------------------+--------------------------+
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/matplotlib/markers.py in set_marker(self, marker)
    247             try:
--> 248                 Path(marker)
    249                 self._marker_function = self._set_vertices

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/matplotlib/path.py in __init__(self, vertices, codes, _interpolation_steps, closed, readonly)
    136         else:
--> 137             vertices = np.asarray(vertices, np.float_)
    138 

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/numpy/core/numeric.py in asarray(a, dtype, order)
    473     """
--> 474     return array(a, dtype, copy=False, order=order)
    475 

ValueError: could not convert string to float: 'go'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-4-e65fc2a3d422> in <module>()
----> 1 RE(plan)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in __call__(self, plan, subs, **metadata_kw)
    527                 exc = self._task.exception()
    528                 if exc is not None:
--> 529                     raise exc
    530 
    531         return self._run_start_uids

/home/xf11id/conda_envs/collection/lib/python3.5/asyncio/tasks.py in _step(***failed resolving arguments***)
    237                 # We use the `send` method directly, because coroutines
    238                 # don't have `__iter__` and `__next__` methods.
--> 239                 result = coro.send(None)
    240             else:
    241                 result = coro.throw(exc)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _run(self)
    692             logger.error("Run aborted")
    693             logger.error("%s", err)
--> 694             raise err
    695         finally:
    696             self.state = 'idle'

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _run(self)
    665                     logger.debug("Processing message %r", msg)
    666                     self.debug("About to process: {0}, {1}".format(coro, msg))
--> 667                     response = yield from coro(msg)
    668                     self.debug('RE.state: ' + self.state)
    669                     self.debug('msg: {}\n  response: {}'.format(msg, response))

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in _open_run(self, msg)
    804         doc = dict(uid=self._run_start_uid, time=ttime.time(),
    805                    **self._metadata_per_run)
--> 806         yield from self.emit(DocumentNames.start, doc)
    807         self.debug("*** Emitted RunStart:\n%s" % doc)
    808         logger.debug("Starting new run:  %s", self._run_start_uid)

/home/xf11id/conda_envs/collection/lib/python3.5/asyncio/coroutines.py in coro(*args, **kw)
    204         @functools.wraps(func)
    205         def coro(*args, **kw):
--> 206             res = func(*args, **kw)
    207             if isinstance(res, futures.Future) or inspect.isgenerator(res):
    208                 res = yield from res

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in emit(self, name, doc)
   1135         self._lossless_cb_registry.process(name, name.name, doc)
   1136         if name != DocumentNames.event:
-> 1137             self.dispatcher.process(name, doc)
   1138             logger.info("Emitting %s document: %r", name.name, doc)
   1139         else:

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/run_engine.py in process(self, name, doc)
   1157 
   1158     def process(self, name, doc):
-> 1159         self.cb_registry.process(name, name.name, doc)
   1160 
   1161     def subscribe(self, name, func):

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/utils.py in process(self, sig, *args, **kwargs)
    149             for cid, func in self.callbacks[sig].items():
    150                 try:
--> 151                     func(*args, **kwargs)
    152                 except ReferenceError:
    153                     self._remove_proxy(func)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/utils.py in __call__(self, *args, **kwargs)
    230             mtd = self.func
    231         # invoke the callable and return the result
--> 232         return mtd(*args, **kwargs)
    233 
    234     def __eq__(self, other):

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/callbacks/core.py in __call__(self, name, doc)
     23     def __call__(self, name, doc):
     24         "Dispatch to methods expecting particular doc types."
---> 25         return getattr(self, name)(doc)
     26 
     27     def event(self, doc):

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/bluesky/callbacks/core.py in start(self, doc)
    150         label = " :: ".join(
    151             [str(doc.get(name, ' ')) for name in self.legend_keys])
--> 152         self.current_line, = self.ax.plot([], [], label=label, **self.kwargs)
    153         self.lines.append(self.current_line)
    154         self.legend = self.ax.legend(loc=0, title=self.legend_title).draggable()

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1810                     warnings.warn(msg % (label_namer, func.__name__),
   1811                                   RuntimeWarning, stacklevel=2)
-> 1812             return func(ax, *args, **kwargs)
   1813         pre_doc = inner.__doc__
   1814         if pre_doc is None:

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axes/_axes.py in plot(self, *args, **kwargs)
   1422             kwargs['color'] = c
   1423 
-> 1424         for line in self._get_lines(*args, **kwargs):
   1425             self.add_line(line)
   1426             lines.append(line)

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axes/_base.py in _grab_next_args(self, *args, **kwargs)
    384                 return
    385             if len(remaining) <= 3:
--> 386                 for seg in self._plot_args(remaining, kwargs):
    387                     yield seg
    388                 return

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axes/_base.py in _plot_args(self, tup, kwargs)
    372         ncx, ncy = x.shape[1], y.shape[1]
    373         for j in xrange(max(ncx, ncy)):
--> 374             seg = func(x[:, j % ncx], y[:, j % ncy], kw, kwargs)
    375             ret.append(seg)
    376         return ret

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axes/_base.py in _makeline(self, x, y, kw, kwargs)
    279         self._setdefaults(default_dict, kw, kwargs)
    280         seg = mlines.Line2D(x, y, **kw)
--> 281         self.set_lineprops(seg, **kwargs)
    282         return seg
    283 

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axes/_base.py in set_lineprops(self, line, **kwargs)
    187     def set_lineprops(self, line, **kwargs):
    188         assert self.command == 'plot', 'set_lineprops only works with "plot"'
--> 189         line.set(**kwargs)
    190 
    191     def set_patchprops(self, fill_poly, **kwargs):

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/matplotlib/artist.py in set(self, **kwargs)
    935                raise TypeError('There is no %s property "%s"' %
    936                                (self.__class__.__name__, k))
--> 937             ret.extend([func(v)])
    938         return ret
    939 

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/matplotlib/lines.py in set_marker(self, marker)
   1069 
   1070         """
-> 1071         self._marker.set_marker(marker)
   1072         self.stale = True
   1073 

/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/matplotlib/markers.py in set_marker(self, marker)
    250             except ValueError:
    251                 raise ValueError('Unrecognized marker style'
--> 252                                  ' {0}'.format(marker))
    253 
    254         self._marker = marker

ValueError: Unrecognized marker style go

In [5]: 

```

**Comment by danielballan** [comment] 2016-01-27 23:57
Victory! Another case closed.

**Closed as completed by danielballan** 2016-01-27 23:57 UTC
