### ISSUE TITLE
Area detector - dark images

### ISSUE THREAD

**Issue by dooryhee** [NSLS-II/Bug-Reports#6] opened 2015-05-08 19:52 UTC
Collect dark images every N light images, N is user-defined. At XPD, N > 1 does not work.

**Comment by danielballan** [comment] 2015-05-08 19:57
Thanks for the report. We have begun looking into the origin of this problem. Having consulted Daron and Tom, we do not believe there is any problem with your fast shutter, so once that that shutter is in use again the issue will be effectively resolved.

The problem may be in using your main shutter to take dark images. We might be able to help you workaround that issue, pending our marching orders from Wah-Keat.

**Comment by tacaswell** [comment] 2015-11-06 02:34
Duplicate of #8 which I believe has been fixed.

**Closed as completed by tacaswell** 2015-11-06 02:34 UTC
