### ISSUE TITLE
Pe1 delay issue

### ISSUE THREAD

**Issue by sghose** [NSLS-II/Bug-Reports#51] opened 2015-11-03 23:13 UTC
I am not sure about the problem. But, while working with Tim today, we found this delay about 5 sec from the timestamp of tiff file. But, then I found the delay comes from tiff squashing. When we made the pe1.num_images = 1 pe1.num_filter = 1 , there is overhead of about .5 sec. So, seems there is no delay associated except the 0.5 sec overhead. We need to check this thoroughly.

**Comment by tacaswell** [comment] 2015-11-04 22:50
duplicate of #49

@sghose Please add comments to that issue.

**Closed as completed by tacaswell** 2015-11-04 22:50 UTC
Labels: XPD
